# =========================
# Peaceful Academy — Netlify config
# =========================

# Netlify configuration for Peaceful Academy

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon"]

# Redirect root to splash.html
[[redirects]]
  from = "/"
  to = "/splash.html"
  status = 200
