# Netlify configuration for Peaceful Academy with Neon (Postgres)
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon"]

# Redirects: send root traffic to app.html
[[redirects]]
  from = "/"
  to = "/app.html"
  status = 200

