# =========================
# Peaceful Academy — Netlify config
# =========================

# Netlify configuration for Peaceful Academy

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon"]


# API first, so it isn't shadowed by any catch-all
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Then the root redirect
[[redirects]]
  from = "/"
  to = "/splash.html"
  status = 301
  force = true

# Optional SPA fallback, last
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
