# Netlify configuration for Peaceful Fields Academy with Neon (Postgres)
[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

# Context-specific settings (env vars should be set in Netlify UI)
[context.production]

[context.deploy-preview]

[context.branch-deploy]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Route /admin to the admin SPA
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200