# =========================
# Peaceful Academy — Netlify config
# =========================

# ---------- Redirects / Rewrites ----------

# 1) Show splash as the root page
[[redirects]]
  from = "/*"
  to = "/splash.html"
  status = 200
  force = true
