
# HTML: always revalidate
[[headers]]
  for = "/*"
  [headers.values]
  # HTML files (index.html, splash.html, reports.html if any) will be no-cache by default
  # Netlify matches most specifically later; we’ll override assets next.
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"

# Static assets can be long-cached **if** you version them (hash or ?v=)
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"


# Netlify configuration for Peaceful Academy with Neon (Postgres)
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon"]

# Redirects
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/reports/annual"
  to = "/.netlify/functions/reports-annual"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

