# Netlify configuration for Peaceful Fields Academy with Neon (Postgres)
[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Route /admin to the admin SPA
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  LOG_LEVEL = "warn"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  LOG_LEVEL = "debug"


 