# Netlify configuration for Peaceful Fields Academy with Neon (Postgres)
[build]
  publish = "."

[functions]
  directory = "admin/netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon","argon2","jose","zod","nanoid"]
  # Remove included_files unless the file really exists at this path:
  # included_files = ["admin/sql/schema.sql"]

# Route /admin to your SPA entry
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200

# Pretty path for the Netlify Function
[[redirects]]
  from = "/api/acellus-import"
  to = "/.netlify/functions/acellus-import"
  status = 200
