# =========================
# Peaceful Academy — Netlify config
# =========================

# Netlify configuration for Peaceful Fields Academy with Neon (Postgres)
[build]
  publish = "admin"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/neon"]
  included_files = ["admin/sql/schema.sql"]

# Admin UI lives under /admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
